function allowDrop(event) {
  event.preventDefault();
}
  
function drag(event) {
  event.dataTransfer.setData("text/plain", event.target.id);
  window.dat=event.target.id;
  console.log(dat); //mon1
  var index1 = dat.indexOf("mon");
  console.log(index1);  //0
  index1=index1+3;
  window.index=index1; 
}
  
function drop(event) {
  event.preventDefault();
  var data = event.dataTransfer.getData("text/plain");
  console.log(data);  //mon1
  event.target.appendChild(document.getElementById(data));
}

/*dictionary to map the monuments and coreesponding states*/
var dict = {
  "monuments/mon1.png": "states/up.png","monuments/mon2.png": "states/maharashtra.png","monuments/mon3.png": "states/rajasthan.png","monuments/mon4.png": "states/up.png","monuments/mon5.png": "states/uttarakhand.png",
  "monuments/mon6.png": "states/up.png","monuments/mon7.png": "states/goa.png","monuments/mon8.png": "states/maharashtra.png","monuments/mon9.png": "states/tn.png","monuments/mon10.png": "states/telangana.png",
  "monuments/mon11.png": "states/maharashtra.png","monuments/mon12.png": "states/sikkim.png","monuments/mon13.png": "states/gujarat.png","monuments/mon14.png": "states/up.png","monuments/mon15.png": "states/maharashtra.png",
  "monuments/mon16.png": "states/tn.png","monuments/mon17.png": "states/punjab.png","monuments/mon18.png": "states/mp.png","monuments/mon19.png": "states/karnataka.png","monuments/mon20.png": "states/rajasthan.png",
  "monuments/mon21.png": "states/kerala.png","monuments/mon22.png": "states/manipur.png","monuments/mon23.png": "states/rajasthan.png","monuments/mon24.png": "states/rajasthan.png","monuments/mon25.png": "states/assam.png",
  "monuments/mon26.png": "states/uttarakhand.png","monuments/mon27.png": "states/hp.png","monuments/mon28.png": "states/mp.png","monuments/mon29.png": "states/meghalaya.png","monuments/mon30.png": "states/gujarat.png",
  "monuments/mon31.png": "states/tn.png","monuments/mon32.png": "states/bihar.png","monuments/mon33.png": "states/tn.png","monuments/mon34.png": "states/rajasthan.png","monuments/mon35.png": "states/karnataka.png",
  "monuments/mon36.png": "states/haryana.png","monuments/mon37.png": "states/karnataka.png","monuments/mon38.png": "states/sikkim.png","monuments/mon39.png": "states/gujarat.png","monuments/mon40.png": "states/chhattisgarh.png",
  "monuments/mon41.png": "states/mp.png","monuments/mon42.png": "states/mp.png","monuments/mon43.png": "states/goa.png","monuments/mon44.png": "states/mizoram.png","monuments/mon45.png": "states/gujarat.png",
  "monuments/mon46.png": "states/odisha.png","monuments/mon47.png": "states/up.png","monuments/mon48.png": "states/andhrap.png","monuments/mon49.png": "states/tripura.png","monuments/mon50.png": "states/wb.png", 
  "monuments/mon51.png": "states/nagaland.png","monuments/mon52.png": "states/nagaland.png","monuments/mon53.png": "states/arunachalp.png","monuments/mon54.png": "states/arunachalp.png","monuments/mon55.png": "states/arunachalp.png",
  "monuments/mon56.png": "states/jharkhand.png" };

/*Declaring variable arrays to store hints*/
var andhrap=["This state shares its capital with an another state","Kuchipudi, one of six classical dance styles of India is the main dance of this state","This state has the second longest coastline in India after Gujarat"];
var arunachalp=["This is the east most state of India","This states is the largest Seven Sisters State","The state's mountain ranges are described as 'the place where the sun rises' in historical Indian texts and named the Aruna Mountains, which inspired the name of the state"];
var assam=["This state is known for its tea and silk","Bihu is the folk dance of this state as well as its famous festival","This state is called the land of Blue Hills and Red River"];
var maharashtra=["The second largest slum in Asia is located in this state","The Commercial capital of India is in this state","This is the second most populous state of India"];
var karnataka=["This state is also known as the Land of Sandalwood, Gold and Coffee","This state is said to have the most number of waterfalls in India","This state is the largest South Indian state"];
var punjab=["This state has a joint capital with an another state","This state is known as the land of five rivers","This state is called the Granary of India"];
var haryana=["This state is known as the battle hub","This state host ancient connections such as the harappan civilization","This state borders the national capital"];
var sikkim=["This state has 11 official languages","This state is the least populated state","This state is home to the highest peak of India and the third highest peak in the world"];
var kerala=["This state is known as the Land of Coconut Trees And Backwaters","The most literate state in India","This state is also called God's own Country"];
var telangana=["This state came into existence in 2014","This state shares its capital with an another state","This state is a bilingual state"];
var tn=["The oldest living language is used in this state","This state has the best and the most visited hill stations all over India","This is the south most state of India"];
var hp=["This state has Highest Cricket Ground in the World","This state is currently the north most state in India","This state is known for its handloom industry"];
var gujarat=["Garba is a famous dance form in this state","Ganthia, Fafda, Chakri, Mathia are all famous foods of this state","This state is home to the only wild population of the Asiatic lion in the world"];
var rajasthan=["The largest state of India","The Great Indian desert is situated in this state","This state is often known as the most colour-coordinated state"];
var up=["This State is the birthplace of Lord Rama and Lord Krishna",	"One of the seven wonders of the world is situated in this state",	"This state is the largest producer of wheat and sugarcane"];
var manipur=["This state is known as the land of gems","This state is known as the land of Gandharvas","Raas Leela is one of the famous dance form of this state"];
var meghalaya=["This state is known as the abode of clouds","The wettest place in the country is situated in this state","This state is home to the Living Root Bridges"];
var bihar=["This state is the Birthplace Of Jainism And Buddhism"	,"This states is called the Land Of IAS Officers",	"This is the third most populous state of India"];
var chhattisgarh=["This state is shaped as a sea horse","This state is famous for its Kosa silk","This state is called the Rice Bowl of India"];
var goa=["It is the smallest state of India","This state has the highest per capita income in India","This state is popular for its beaches and churches"];
var jharkhand=["This state is also called Chota Nagpur","This state is one of the richest mineral zones in the world","The literal meaning of the anme of this state is the Land of Bush or Forest"];
var mizoram=["This state is called the Land of Blue Mountains","Cheraw dance is a traditional cultural dance performed in this state","The biggest family in the world lives in this state"];
var mp=["This state is known as the Heart of India","This state is the second largest Indian state by are","The state animal of this state is the beautiful swamp dear Barasingha"];
var nagaland=["This state is also known as the Land of Festivals, there are festivals for each month of the year","The state has 15 plus tribes and a whopping 36 different languages within its boundary, making it perhaps the most vibrant of all the Indian states","This state is called the 'Falcon Capital of the World' owing to the conservation efforts for the Amur Falcon"];
var odisha=["This state is home to the white bengal tigers","This state is India’s most advanced missile testing site","This state in mentioned in the national anthem of India by the name of Utkala"];
var tripura=["This state shares borders with Bangladesh","This state is known for its bamboo and cane architecture","Third smallest state of India"];
var uttarakhand=["This state is known as Devbhoomi-the land of gods","Two largest and holiest rivers of India- Ganga and Yamuna originate from this state","This state is also known as the abode of Pandavas"];
var wb=["Durga Puja is the biggest, most popular and widely celebrated festival in the state","This state is famous for its sweets","This state is home to Sundarbans, the largest mangrove forest in the world"];

/*Declaring variable arrays to store facts*/
var mon1=["In 1983, the Agra fort was inscribed as a UNESCO World Heritage Site", "In A.D. 1530, Humayun was crowned in Agra Fort", "Most part of the fort is made of red sandstone","Although it is a classic example of Islamic architecture, the Agra fort has a separate section for Hindu temples and places where Hindu people would worship their gods","Agra Fort was home to Shah Jahan’s famous peacock throne that had the world famous Koh-i-Noor diamond. Nadir Shah, the Persian ruler attacked the fort and looted the throne"];
var mon2=["Though the caves are over 2,000 years old, the Buddha statues were added close to 600 years later","The Ajanta Caves include 30 rock-cut Buddhist cave monuments dating back to the 2nd century BCE to 480 CE","The Ellora Caves are a combination of 34 caves","Ajanta Caves display Viharas and Buddhist monasteries and Ellora Caves consists of religious centers for Hindu, Buddhist, and Jain","Since 1983, Ajanta caves have been listed among the UNESCO World Heritage Sites of India"];
var mon3=["It was constructed in the 8th century by Ajayraj Chauhan","Ajmer Fort is guarded by magnificient Aravalli ranges","Ajmer Fort is the religious place of Muslim and an embarking tour of spiritual place Pushkar for Hindus","At the top of the Nag, Pahari Hill stands Ajmer Fort also called the Taragarh fort, which is the oldest hill fort in the world. It dates back from the 12th century","Another form is known as “Starfort”, it offers the bird’s eye view of the whole city in Ajmer","Adhai Din ka Jhonpra is a historic mosque on the lower slopes of Taragarh hill built by Qutub Ud Din Aibak"];
var mon4=["Following the Timurid tradition, Akbar the Great had started to build his own tomb at Sikandra but he died during its construction and his son Jahangir completed it in 1613","Akbar's tomb complex is built in a perfectly symmetrical complex, with the tomb located in the centre of a vast walled garden","The tomb that we can see in the chamber is a replica tomb; the original tomb is buried underground and can only be accessed by family members","During the reign of Aurangzeb, Jats rose in rebellion under the leadership of Raja Ram Jat. The Jats ransacked Akbar's tomb, plundering and looting the gold, jewels, silver and carpets, amd destroying what they could'nt loot. According to one account, the grave was even opened and the late king's bones were burned","As Viceroy of India, George Curzon directed extensive repairs and restoration of Akbar's mausoleum, which were completed in 1905"];
var mon5=["Lord Vishnu once sat at this place for meditation according to Hindu legend. The weather was really cold and Goddess Laxmi protected him in the form of a berry tree. When Lord Vishnu got to know about it, he was impressed by the devotion of Goddess Laxmi and called the tree, Badri Vishal","Badrinath is set between two mountains - Nar and Narayana. It is believed that two hermits Nar and Narayana, both incarnation of Lord Vishnu in Satyug, meditated here and were born as Arjun and Lord Krishna in Treta Yuga","Badrinath is one of the four Char Dham pilgrimage sites in India","Divya deshams are the most important Vishnu temples mentioned by Tamil saints. There are 108 divya deshams of which 105 are in India. Badrinath Temple located in Uttarakhand is one among these holy shrines"];
var mon6=["In 1784 a major famine struck the Awadh region; rendering the people of the province rather helpless. It was then that the Nawab of Awadh, Asaf-us-Daula decided to involve all the people into the construction of this monument. It is believed that labour class spent the day constructing and in the evening, the aristocracy would come and destroy it! This ensured work to all classes of people. The construction and famine both lasted for 11 years and so did the employment scheme! It is believed 20,000 men were involved in the making of this monument!","Its central hall is said to be the largest unarched hall in the world. This central foyer ceiling has no beams and support to hold it to its glory","The biggest attraction of the Bada Imambara is the infamous Bhool Bhulaiya! With 1024 ways of going in and only 2 to come out, this maze is situated on the top of the Imambara. Many interconnected passages of the Bhool Bhulaiya were closed to the general public after some people were reported missing","It is believed that there are secret tunnels in the Bara Imambara which lead directly to the Gomti River, Delhi, Faizabad and Allahabad","On the Eastern side of the magnificent Bara Imambara is the Shahi Baoli or the step-wise well. This is said to be the secret surveillance system of the Nawab and his officials, for if you stand in the inner Eastern chamber of the well, you can see the reflection of those approaching the well from the other side in the water"];
var mon7=["This impressive church in Old Goa is one of the UNESCO World heritage sites of India","The church was built using Baroque architectural style, which was the most popular style of architecture in the sixties. This is a heavily adorned and ornamental form of architecture, making the church a visual treat. The floor of the church is laid with marble and the interiors are done with precious stones and other ornamental works","Being a 400 year old church, the church is not only among the oldest churches in Goa, it is also one of the oldest churches in the world","Basilica of Bom Jesus holds the tomb and mortal remains of St. Francis Xavier, whose body was brought from China to the church after two years of his death. It was discovered that the saint\'s body remained intact as the day it was buried","Many of the important buildings and corridors of this church were destroyed due to the fierce fire in 1663, but in 1783 the church was repaired. The upper story of this church was demolished between 1886 and 1887","This Goa church is the best example of Baroque architecture. Everyone calls this church by the name ‘Bom Jesus’, it means ‘good Jesus’ or ‘little Jesus’"];
var mon8=["Bibi ka Maqbara was built by Shah Jahan's son, Aurangzeb in the late 17th century in loving memory of his first wife Dilras Banu","Bibi ka Maqbara was designed and established by the architect Ata-Ullah, along with an engineer named Hanspat Rai. The marble, with which this monument is constructed, was bought from mines near Jaipur, Rajasthan","Bibi-ka-Maqbara is also called the 'Dakkhani Taj' (Taj of the Deccan). It is so designed that it's reflection falls on the pond in the garden when the Sunlight hits the mausoleum. It is also called a poor man's Taj Mahal because of poor imitation. It is not entirely made of marbles","Bibi Ka Maqbara is believed to have been built between 1668 and 1669 C.E. According to the 'Tarikh Namah' of Ghulam Mustafa, the cost of construction of the mausoleum was Rs. 668,203-7 (rupees six lakh, sixty-eight thousand, two hundred three and seven annas) – Aurangzeb allocated only Rs. 700,000 for its construction"];
var mon9=["The Brihadeeswarar temple along with Airavatesvara temple and Gangaikonda Cholapuram is known as the ‘Great Living Chola Temple’ and is part of the UNESCO World Heritage Site","Brihadeeswarar temple, which is dedicated to Shiva, was built by Raja Raja Chola I. The construction was completed in 1010 which it means that the temple is more than 1000 years old","According to the inscriptions present in the Brihadeeswara temple, Kunjara Mallan Raja Raja Perumthachan was the engineer and architect of this famous temple","The temple has the world’s tallest vimanam (temple tower) and its Kumbam (the structure on the top) weighs approximately 80 tons. The temple has a huge statue of Nandi (sacred bull) at the entrance. The statue is carved out of a single rock and weighs around 20 tons","Brihadeeswarar temple is one of the few temples that have Ashta-dikpaalakas (Guardians of the directions) idols. Chola frescoes adorn the wall of the temple and these frescoes depict Shiva in different poses","Brihadeeswarar temple is the first complete granite temple in the world. Around 60,000 tons of granite is said to be used to build the temple"];
var mon10=["According to a theory, the massive structure of Char Minar was built to commemorate the end of the plague epidemic. Looking at his city in distress, the ruler had prayed that he would build a mosque if and when the plague menace ends","As per legends, there is an underground tunnel built in Char Minar to connect the Golconda Fort, which was the former capital of Quli Qutb Shah to Charminar. It is believed that the king built the tunnel as an escape route in case of any siege. The location of the tunnel is still a mystery","One of the arches on the eastern side of the Char Minar has a cat’s head carved in it. The mosque was built to mark the end of plague. Since, plague is spread by infected rats and cats kill rats, the latter was included in the architecture to represent its role in eradicating the disease","A set of four clocks have been keeping close watch on Char Minar since 1889! These clocks are set on the four arches facing the former royal streets in four cardinal directions. The 150-year old clocks had travelled from London during the rule of Mir Mehbood Ali Khan"];
var mon11=["Chhatrapati Shivaji Terminus took 10 years for construction","The British architectural engineer Frederick William Stevens who designed the iconic structure of Chhatrapati Shivaji Terminus was all of 31 years old when construction on the building began in 1878. He was paid $24,000 for the job","Services of the students from JJ School of Art were enlisted to create certain ornamental elements of the building of Chhatrapati Shivaji Terminus. The students worked under the watchful eye of John Lockwood Kipling, who we know better as the father of an author called Rudyard Kipling","Chhatrapati Shivaji Terminus is the first ever railway station in India , formerly built as the Victoria Terminus Railway Station, named after the then reigning queen , and has been subsequently renamed in the honour of the great Maratha king Chhatrapati Shivaji Maharaj","The first historic passenger train in India was operated from Bori Bunder to Thane on April 16, 1853. The station is now home to the Central Railway Headquarters","On 2nd July 2004, Chhatrapati Shivaji Terminus was nominated as a world heritage site by UNESCO"];
var mon12=["Established in 1701, Dubdi Monastery is professed to be the oldest monastery in Sikkim","Dubdi, also called Yuksum (Yuksom) Monastery, belongs to the Nyingma sect of Tibetan Buddhism","Dubdi Monastery was also known as the Hermit's Cell after its ascetic founder Lhatsun Namkha Jigme, who along with two other lamas from Tibet met at Norbugang near Yuksom and crowned Phuntsog Namgyal as the first King or Chogyal of Sikkim at Norbugang Yuksom in 1642","The word 'Dubdi' in the vernacular tongue means 'the retreat'","The Dubdi Monastery provides a magnificent bird's eye view and enables visitors to witness cupressus funebris, a species of cypress brought by Latshen Chem Po from Kham village in Tibet"];
var mon13=["It is believed that the Dwarkadhish Temple in its original form was constructed by Vajranabh, the Great Grandson of Lord Krishna. It was built over the residential palace of Lord Krishna","The Dwarkadish temple has two dwars or gates. One is the Swarg Dwar, the gate to heaven and a Moksha Dwar, the gate to liberation. All the devotees who enter the temple have to climb 56 stairs to enter the gate of heaven and they exit through the gate of liberation","According to a legend, the original city that was built by Lord Krishna actually got submerged in the sea. An underwater excavation that took place a few years ago confirmed that there were architectural remains under the sea. According to the legend, when Lord Krishna was meditating under a tree in a forest, he was accidentally shot by an arrow and he left for heavenly abode. After Lord Krishna's death, there was a flood in the city and everything submerged into the ocean","The 15th-century old Dwarkadish temple has a black coloured idol of Lord Krishna which was designed limestone as per the Chalkya style","The Dwarkadhish temple, also known as Jagat Mandir is considered one of the four dhams of worship which were visited by Adi Shankaracharya back in the 8th century. The other char dhams were Badrinath, Rameshwaram, and Puri"];
var mon14=["The Fatehpur Sikri city complex was founded in the 16th century. It was during the year 1571 when the city was founded as the capital of the Mughal Empire by the then Emperor Akbar","The Mughal capital was soon moved to Delhi in 1586 because of Fatehpur Sikri’s inadequate water supply","Fatehpur Sikri was designated a UNESCO World Heritage Site in 1986 because of its existence as a huge complex of monuments and temples, all in a uniform architectural style that also includes one of the largest mosques in India, the Jama Masjid","Fatehpur Sikri is an Arabic name: Fateh means 'Victory' and Sikri means 'thanks to God'","Akbar was heirless for a long time. He heard about Salim Chisti who was then a famous Sufi Saint in Sikri. He went to visit Salim Chisti to seek his blessing for a child. Salim blessed him and predicted that he will soon get a baby from his wife Jodhabai within the next 2 years. Later as predicted by Sufi Saint, Akbar’s son Jahangir was born on 31 August 1569 at Sikri. The Fatehpur Sikri monument was built by Akbar to honour Sheikh Salim Chisti", "Buland Darwaza, the highest gateway in the world, is a 54-metres high gate built in Fatehpur Sikri in the year 1602. It was built by Akbar in the memory of the victory in Gujarat in 1601. It took nearly 12 years to make the highest gateway"];
var mon15=["Gateway of India was built as a triumphal arch to commemorate the visit of King George V and Queen Mary to Mumbai, prior to the Delhi Durbar in December 1911","The foundation stone of Gateway of Indiawas laid by the then Governor of Bombay (Mumbai) on March 31st 1913", "Gateway of India is built from yellow basalt and reinforced concrete, which is facing out to Mumbai Harbour from the tip of Apollo Bunder", "George Wittet was the chief architect of the Gateway of India", "Gateway of India was completed in 1924 at a cost of Rs. 24 lakh. Its structural design is constituted of a large arch, with a height of 26m", "First Battalion of the Somerset Light Infantry passed through the Gateway on their way out in a ceremony on February 28, 1948, signalling the end of British rule", "Gateway of India serves upto five jetties, the first one is used by Atomic Research Center exclusively, the second and the third are used for commercial ferry operations, the fourth is closed, and the fifth is used by Royal Bombay Yatch club"];
var mon16=["Located around 160 km from Chennai, in Villupuram district of Tamil Nadu, lies one of the most important and powerful forts of South India -the Gingee Fort, also known as Jinji or Senji", "Once the seat of great medieval powers jousting for supremacy, Gingee Fort's great fortifications and its reputation as being 'impregnable' led medieval European travellers to dub it the 'Troy of the East'. In fact, the Mughal army could only capture it after a siege of eight years, the longest one recorded in Mughal history!", "Apparently, the name 'Gingee' or 'Senji' in Tamil is derived from the shrine of local goddess 'Senjiammman', which predates the construction of the fort", "A small fort was constructed during the time of Chola dynasty. Later, it was revamped by the Kurumbas (who ruled for sometime). The present structure was built by Gingee Nayaks in the 15th and 16th century", "The area around Gingee was notorious for malaria. Plagued by the disease, in 1716, the Mughals shifted their headquarters from Gingee to Arcot. During the British and French wars for supremacy of the Tamil Nadu coast, the French conquered Gingee in 1750. For the 10 years that they held the fort, the French lost 1,200 soldiers to malaria", "In 1920, the Gingee Fort was declared a protected monument under the Archaelogical Survey of India"];
var mon17=["Records show that Lord Buddha stayed at the sacred site of the Golden Temple for quite some time. In those times, the spot was a lake surrounded by thick forests. Buddha declared this site as an ideal meditation ground for sadhus and saints", "The Golden Temple that you see today interestingly wasn’t covered with an inch of gold when it was first constructed. In the year 1762, this religious heritage site was complete, destroyed by Islamic rulers. After the devastation, Maharaja Ranjit Singh, a brave Sikh ruler rebuilt the rich heritage with marble and adorned it with gold", "The foundation stone of the auspicious Golden Temple was laid by a famous Sufi saint Mian Mir. This was done to spread a message that this sacred gurudwara is open to all faiths. There are four entrances to the temple which shows openness to all devotees irrespective of caste, creed and religion", "As the Golden Temple is uniquely set up at a lower level below the ground, the stairs leading to the shrine go downwards. This is quite contrary to the Hindu temples that are always built on an elevated platform above the ground. This distinct feature at the Golden Temple signifies humble living", "The langar sewa at the Amritsar Golden Temple is the largest free kitchen in the world. It serves more than fifty thousand meals on a daily basis"]; 
var mon18=["The king who ruled Gwalior was suffering from leprosy, a disease with no cure during those times. A sage, Gwalipa visited the palace and cured him. The king renamed his city after the sage. The sage cured the disease by offering water for a pond and the king built a fort, which included the region of the pond and named it as Gwalior fort", "The Gwalior Fort was built in 8th century and up to British rule, the fort was under the possession of different kings. The fort was used as a political prison for royal people during the rule of Mughals. For instance, Akbar’s cousin was held in the fort as a prisoner and was executed there", "The second oldest record of usage of ‘zero’ in mathematics is found in a temple in the Gwalior Fort. The inscription is roughly 1500 years old", "A Tamarind Tree stands inside the Gwalior Fort complex, which is said to be planted by Tansen, the great musician of his time. There is a common rumor of misbelieve that eating the leaves of this tree can sweeten ones voice like that of Tansen", "Sas Bahu Temple inside the Gwalior Fort has both Shiva and Vishnu statues. These two Gods were worshipped by different clans during ancient time. In 9th century, a royal mother-in-law and daughter-in-law fought about which deity to worship and this strange temple was built to satisfy them both"];
var mon19=["A standout amongst the most appealing structures of Hampi is the Vittala Temple. It is known for its 56 melodic columns or the musical pillars. These pillars create melodic sounds when tapped delicately. The most intriguing thing is that the columns are constructed using stones. The melodic mainstays of Vittala Temple are also called SAREGAMA pillars", "The primary historical record of settlement in Hampi goes back to 1st Century. Evidence shows that the district of Hampi was under the governor of Ashokan Kingdom amid the third century BC", "Hampi was originally called Pampa-Kshetra after Hindu Deity Pampa (another name of Goddess Parvati). It is believed in Hindu mythology that Goddess Parvati led the life of a yogini in the Hemkunta hills of Hampi, to convince Shiva to marry her", "Hampi is believed to be the monkey kingdom Kiskinda, where Lord Ram met his loyal follower Hanuman. The monkey army later helped Rama build a bridge of stones across the sea to help him reach Lanka", "Spread over 4000 hectares, Hampi was the second largest city in the medieval world, next only to Beijing. It was one of the biggest international trade centers in the world in the 14th and 15th century"];
var mon20=["Hawa Mahal was built by Rajput Sawai Pratap Singh in 1799", "Hawa Mahal is built in the shape of a crown. It is said to look like Lord Krishna's crown", "Hawa Mahal means the 'Palace of Winds' or the 'Wind Palace'. It has 953 small windows (Jharokas), they were built to keep the wind blowing inside the palace", "Hawa Mahal stands upright because of its pyramidal shape. It is a five-storey building, but due to the lack of solid foundations, it is curved and leans at an angle of 87 degree. Further, its distinctive rosy colour, which is because of the natural sandstone, is the reason behind Jaipur getting its nickname, .i.e., the Pink City", "Hawa Mahal is the tallest building in the world without a foundation", "Hawa Mahal is believed that it was built so that the Royal ladies could enjoy the street functions and festivals without being revealed to the audience, without any disagreement to their Purdah System"];
var mon21=["Built in 1865, the Hill Palace Museum is famous for being a full-fledged Ethno-Archaeological Museum and Kerala's first ever Heritage Museum", "The Hill Palace complex itself comprises 49 buildings and is built in the traditional Kerala style of architecture. It has over 52 acres of terraced land around it", "Hill Palace was built in 1865 by the Maharaja Of Cochin using his personal wealth", "The Hill Palace museum was opened in 1991. At present, there are 11 galleries. The museum has a collection of ancient artifacts, sculptures, coins, coins and materials belonging to Cochin Maharaja and his royal family"];
var mon22=["ISKCON’s philosophy is taken from Srimad Bhagavad and Bhagavad Gita that existed for many centuries", "Till date, there have been 32 spiritual masters in ISKCON","ISKCON promotes spirituality and not Hinduism. It promotes principles of existentialism taught in Vedas which are applicable to people of all races and religions", "ISKCON preaches love and compassion from the spiritual perspective of Gaudiya Vaishnava", "ISKCON is based on the principles of non-vegetarianism, no alcohol and no violence", "ISKCON follows holy scripts of Bhagwad Gita and Srimad Bhagwat", "People from any religious background can follow the principles taught by ISKCON", "ISKCON promotes Krishna consciousness", "ISKCON promotes good living and wellness that is based on enriching your life at a soul level"];
var mon23=["In 2013, Jaisalmer Fort was declared UNESCO World Heritage Site. This fort is in the first place in the ancient fortifications of the world which is fully preserved", "There are seven Jain temples built on Jaisalmer Fort. The construction of these temples is believed to be in the middle of 15th to 16th century", "Jaisalmer Fort is also known as Sonar Quila or the Golden Fort as it is made of yellow sandstone", "Under the reign of Rawal Lunkarna in 1530-51; Amir Ali, the chief of a local Afghan clan, attacked Jaisalmer Fort. With the pretext of sending his wives to visit Jaisalmer’s queens, Amir Ali sent his warriors to infiltrate the fort. In the ensuing battle, Rawal Lunkarna lost his soldiers and felt that the fort would be lost to the invaders. With not enough time for funeral pyres, he decided to kill the women of the palace himself. In a cruel twist of fate, however, reinforcements arrived soon afterwards, thwarting the invaders and leading to a victory for Rawal Lunkarna. The tragic incident is referred to as the half-Jauhar of Jaisalmer Fort", "The Jaisalmer Fort is the world’s largest desert living fort. Also, it is the second oldest fort in Rajasthan. A major landmark, it has thousands of people living within the premises", "In the time of Maharawal Jaitsi, Alauddin Khilji besieged the Jaisalmer Fort, and 24,000 women from, infants to old, committed Jauhar"];
var mon24=["There were five Jantar Mantars in India, all of them built at the command of the Rajah Jai Singh II, who had a keen interest in mathematics, architecture and astronomy; four remain, as the Jantar Mantar at Mathura was torn down just before the revolt of 1857", "Jantar Mantar is one of the world heritage sites listed by UNESCO", "Though 5 Jantar Mantar observatories were constructed in various parts of India, the one in Jaipur is the largest of them all", "Jantar Mantar was built to study time and space. The structure in Jaipur is a complex of nineteen architectural astronomical instruments, and is still running and being used for calculations and teaching. It is used to observe and study the orbits around the Sun. Some of the structures here were built in stone and marble, and some in bronze", "The words Jantar and Mantar derive from Sanskrit words Jantra and Mantra that mean 'instrument' and 'calculate' respectively, which makes the meaning of Jantar Mantar as 'a calculating instrument'", "Jantar Mantar in Jaipur has the world's biggest stone sundial called as Brihat Samrat Yantra. This instrument gives the local time at the accuracy of two seconds"];
var mon25=["Kamakhya is one of the oldest shakti temples", "Kamakhya symbolizes procreation", "Kamakhya is among the major 18 Maha Shakti Peethas in all 108 Shakti Peethas", "Established in the worship of Goddess Kamakhya, Kamakhya is symbolic of the strength or ‘shakti‘ present in every woman, in the Kalika Purana and Yogini Tantra. These are the sacred texts of Shaktism"];
var mon26=["Katarmal Sun Temple is believed to be built by King Katarmalla; hence the name", "The main deity of Katarmal Temple is the Sun God, known as Burhaditya and Vraddhaditiya which is installed in such a strategic position so that the first rays of the Sun hit the idol once a day every year. This rare occasion is a much celebrated event at Kartarmal Temple", "The Katarmal Sun Temple falls under the list of protected heritage sites of the Archaeological Survey of India (ASI)", "There are at least 44 temples surrounding the main shrine of Katarmal Sun Temple complex- all dedicated to the various deities in Hindu mythology", "Unfortunately, a robbery in the Katarmal Sun Temple complex shed light on a grave situation. The valuable and ancient relics from the temple were then moved to the National Museum in New Delhi for safe keeping"];
var mon27=["The Key monastery is the largest in the valley and holds a powerful sway over the most populous part of the valley around Kaza", "Teautiful Tibetan Key monastery is situated at 4.166 metres above sea level. There are only a handful of people that make it up there", "Key Monastery was destroyed by invaders and rebuilt several times. In 1840 it caught fire and in 1975, it suffered extensive damage due to an earthquake. Having been rebuilt several times, temples and other buildings appear to have been stacked haphazardly", "The walls of the Key Monastery are covered with murals and paintings which are an example of the 14th century monastic architecture which developed as a result of Chinese influence", "Founded by Dromton, a famous disciple of teacher Atisha in the 11th century, the Key monastery used to house about 350 lamas at one time"];
var mon28=["In the Hindi language, the word “Khajura” implies ‘Date’ and the word “Vatika” implies ‘Bearing’. In history, the place “Khajuraho” is labeled with the term Jejakabhukti", "Most of the temple structures at Khajuraho are built in sandstone, along with varying shades of pink, buff and yellow", "During the medieval period, there were 85 temples in Khajuraho, out of which only 22 Hindu temples remain, the rest being ruined due to natural calamities", "The Archaeological Survey of India has ranked Khajuraho monuments as the best preserved monuments of antiquity", "The Khajuraho group of memorials counted as one of the UNESCO World Heritage Site in Madhya Pradesh. These temples got this status in the year 1986. This place is considered to be the largest group of medieval Jain and Hindu temples. It is popular for its erotic sculptures that adorn the shrine"];
var mon29=["Kiang Nongbah Monument was built in the honour of a Jaintia patriot by the name of U Kiang Nongbah who died as a martyr in the struggle to free the Jaintia land from the British rulers", "This historical monument was built in the centre of a vast field known as Madiah Kmai Blai, which is on the banks of Syntu Ksiar, alongside river Myntdu", "The field surrounding Kiang Nongbah has its own historical significance. It is the place where U Kiang Nongbah had taken his oath to fight and drive the British out of their land without fearing any consequences"];
var mon30=["Laxmi Vilas Palas is reputed to have been the largest private dwelling built to date and four times the size of Buckingham Palace", "At the time of construction itself Laxmi Vilas Palace had elevators, a rarity at that time", "The interiors of the Laxmi Vilas Palace resemble a massive country house in Europe", "Laxmi Vilas Palace still houses the members of the erstwhile royal family of Baroda", "Laxmi Vilas Palace has the maximum number of stained glass ever used in a palace"];
var mon31=["The Mahabalipuram group of monuments is a UNESCO World Heritage Site", "There are five chariots in Mahabalipuram dedicated to the Pandavas", "The Mahabalipuram temples were built by three generations of the Pallava Kings and it took 200 years to plan and create the site", "The Shore Temple is the last monument built and was built from the top to the bottom, unlike most others in general", "During the 2004 Tsunami catastrophe, Mahabalipuram temple was the first to get hit in this town but because of its strength, it survived. As per locals the temple complex was thoroughly covered by sand however once the catastrophe was over on clearing the sand there were a few more sculpted monuments etc. that were discovered. These were hidden below the soil before Tsunami came"];
var mon32=["Mahabodhi Temple is believed to be the place where Gautam Buddha attained enlightenment. It was here that sitting under a peepul tree that young prince Siddhartha (who later became Gautam Buddha) attained all the answers he sought after three days and three nights of meditation", "Built by emperor Ashoka in 260 BC, the Mahabodhi temple complex is one of the first Buddhist temples to be built entirely of brick. Being one of eastern India’s oldest brick structures, its architecture has been widely appreciated", "The Mahabodhi Temple complex was declared a UNESCO World Heritage Site in June 2002. Since then, all of its religious artifacts are legally protected", "Apart from the grand statue, the Mahabodhi Temple complex consists of several places of interest to Buddha devotees like the Bodhi tree (a descendant of the tree under which Buddha actually attained enlightenment), the lotus pond and several ancient stupas. These places are associated with the seven weeks Buddha is said to have spent here", "With the decline of Buddhism in India, the Mahabodhi Temple was abandoned and got buried under the layers of sand. It was later restored by Sir Alexander Cunningham along with J.D.Beglar and Dr. Rajendra Lal Mitra who excavated this site", "After building the Mahabodhi Temple, Emperor Ashoka sent his heirs to Sri Lanka and various parts of India to spread Buddhism. He also sent a sapling of the original tree to Sri Lanka. When Muslim invaders destroyed the temple along with the original tree, a sapling from the Sri Lankan tree was brought back to Mahabodhi to grow", "There is a legend that, if the Bodhi Tree was not present in the region, the ground of the Bodhi tree will not allow any plant, not evens a grass to grow. No living being would be able to travel through that region. After the original tree was destroyed, a similar scenario was said to be experienced. It is also said that the location of the tree is the navel of the Earth", "There is a lotus pond in the Mahabodhi Temple, closer to the Bodhi tree. The passage running around the pond has many stone lotus carved. It is said that Buddha spend seven weeks of his life meditating in this region. He performed walking meditation, by walking 18 steps back and forth. The stone lotuses hold faded foot prints of Lord Buddha", "A slab is constructed at Mahabodhi Temple on the spot where Lord Buddha meditated. It is said that if the world gets destroyed, the slab region would be the last place to get destroyed. And, when the world re-forms, the slab would be the first region to form"];
var mon33=["The Meenakshi Temple seen today was rebuilt in the 16th century by Vishwanatha Nayakar who was a Nayak ruler after it was destroyed and looted by Muslim raider Malik Kafur in the 14th century. It is believed that the original structure of the Meenakshi Temple dates back to the 6th century BC", "Meenakshi Temple has the largest temple complex in South India. The temple boasts of a 6-hectare complex which is among the largest temple complexes in the whole of India", "Meenakshi Temple is dedicated to the fish-eyed goddess Meenakshi Amman (or goddess Parvati, as known in the north). ‘Fish-eyed’ is a phrase often used for a perfect pair of beautiful eyes in Tamil poetry", "At the core of the Meenakshi Temple complex are the two sanctums for Meenakshi and Sundareswarar, surrounded by a number of smaller shrines and halls. Meenakshi has a temple to the south, and Shiva, known as Sundareswarar, a temple to the west. Since she is the presiding deity the daily ceremonies are first performed in her shrine and, unlike the practice at other temples, Sundareswarar plays a secondary role", "Meenakshi Temple is nominated among the 30 attractions around the world which have been nominated to be on the list of New Seven Wonders of the World", "Meenakshi Temple has 12 lofty gopurams, out of which 4 major ones are placed facing the four directions. There are 4 inner gopurams that act as the entrances to the shrine. These gopurams are heavily carved, and is reconstructed and cleaned every 12 years", "The Hall of Thousand Pillars at the Meenakshi Temple, or Aayiram Kaal Mandapam is a wonderful piece of architecture and is believed to be built out of a single rock. There are many ancient paintings inside the museum of this temple. This is the only part of the temple that is open to visitors and devotees of all beliefs"];
var mon34=["For the Rathore dynasty, Sun was the most superior of all Gods. Hence, they named the fort ‘Mehrangarh’, a name which was derived from two words: ‘Mihir’, that stands for Sun and ‘Garh’ implicating Fort. The locals gradually began to call Mehar-garh as Mehrangarh in their local accent, hence the name", "According to a legend, a hermit called Cheeria Nathji used to meditate on the hill, where Rao Jodha decided to build the Mehrangarh Fort and had the hermit move from the site. Agonized by this, Nathji cursed Rao’s family saying that his fort would suffer from scarcity of water. To avert the curse, Rao Jodha had built a home and a temple in the fort for Nathji and also had a man named Rajiya Bambi buried alive, to ensure that the new fort was auspicious. In return, the man was offered that his family and descendants would be looked after and compensated by the Rathores. Even today, the Mehrangarh Fort faces draughts every 3-4 years", "There are seven gates to enter the Mehrangarh fort, which were made by different rulers in honor of victory over the Bikaner and Jaipur armies. You can still spot the imprints of cannonballs fired by the Jaipur army at the Dedh Kamgra Gate. To the left of the Loha Gate, are the hand prints of the royal satis, the wives of the rulers. It is said that the satis carried the Bhagavad Gita along with them while sacrificing themselves on the funeral pyre of their husband, but the royal book would not perish", "The massive Mehrangarh Fort was built on a rocky cliff known as Bahuchiriya, the mountain of birds in 1459. It's palaces were built over a period of 500 years following the foundation", "Though the Mehrangarh Fort was originally constructed in mid 15th century by Rao Jodha, the founder of Jodhpur, it was expanded with many palaces and structures by his descendants across 500 years. Most of the fort which stands today dates back to the 17th century and was built by Maharaja Ajit Singh"];
var mon35=["The Mysore Palace gets more than 6 million visitors every year. It is one of the most visited tourist places in India", "The Mysore Palace has an amalgamation of architectural styles. The main Indo-Saracenic architecture has a blend of Hindu, Mughal, Rajput and Gothic Styles", "After the Indian Independence, the Royal Family had to shift to another palace. So, the Mysore Palace was turned into a museum. Museum holds the artefacts, pictures, royal clothing, etc. of the Wodeyars"];
var mon36=["The Jal Mahal, also known as the Jal Mahal of Narnaul or the Water Palace, is a late 16th century palace, fortification, and artificial lake", "The Jal Mahal is situated in the middle of the huge pond known as Khan Sarovar, but there is a bridge to reach the Jal Mahal", "According to a Persian inscription over the main entrance, the Jal Mahal was built by Nawab Shah Quil Khan, who was the Governor of Narnaul for 52 long years", "The pond was filled with soil in over 400 years. In 1993, the district administration started the removal of soil from the pond of Jalmaha"];
var mon37=["Pattadakal Group of Temples, in Karnataka, represents the high point of an eclectic art which, in the 7th and 8th centuries under the Chalukya dynasty, achieved a harmonious blend of architectural forms from northern and southern India", "Pattadakal was the sacred site where the Chalukyan kings were crowned, and many of the temples were built here to commemorate victories", "All the Hindu temples in Pattadakal city are dedicated to Lord Shiva and are noteworthy for their craftsmanship and architectural brilliance"];
var mon38=["Built for Ta Sangs (pure Tibetian monks) in 1705, the three-storeyed Pemyangtse Monastery is one of the most renowned in the state of Sikkim", "The word Pemayangtse mean 'Perfect Sublime Lotus' and it is a famous tourist attraction and widely visited by many travellers all year round"];
var mon39=["The Italian Gothic Style architecture of Prag Mahal is one of the major attractions", "Durbar Hall, Clock Tower, murals and the courtyard are some of the main attractions of Prag Mahal", "Prag Mahal was majorly affected by the earthquake which happened in 2001. Some portions of the building were destroyed. Later, some prominent portions of the building was restored and opened for the public"];
var mon40=["The Ratanpur Fort has many sculptures which are to be that of the God and Goddesses where the visitors are welcomed to visit and have a look at it and put on their prayers before them", "The entrance at the west side of Ratanpur Fort is positioned facing toward the Motipur which is believed to be the place where the twenty Queens of Lakshman Rai had performed sati"];
var mon41=["Bhimbetka is a UNSECO acknowledged World Heritage Site. It has earned that title by being home a set of extraordinary cave paintings made by Man in prehistoric times", "The Rock Shelters found at Bhimbetka show the earliest traces of human existence in India", "The entire region of Rock Shelters found of Bhimbetka comprises more than 600 caves"];
var mon42=["Sanchi Stupa is one of the oldest Buddhist monuments in the country and the largest stupa at the site", "The Great Sanchi Stupa was originally built in the 3rd century BC by the Mauryan emperor Ashoka and is believed to house ashes of the Buddha", "Sanchi Stupa is a UNESCO World Heritage Site. It was the year 1989 when the Sanchi Stupa was declared the world heritage site", "It was from the Ashoka Pillar of Sanchi Stupa that the national emblem of India was derived"];
var mon43=["St. Cathedral Church in Goa is the largest church in Asia", "There are five bells in the St. Cathedral Church house, Golden bells being the most famous and big among them. It is said that the sound of this bell is heard throughout the state", "It is said that St. Cathedral Church took nearly 90 years to build this church. It was started to be built in 1562", "St. Cathedral Church has 14 altars, each of which is beautifully carved and the main altar is plated with gold that traces the life of Red Ros and Saint Catherine of Alexandria"];
var mon44=["Solomo's Church is made purely of white marble", "The walls of Solomon's Church exactly face South, North, East, and West", "The foundation of Solomon's Church was laid on December 23, 1996. It took almost two decades to complete the construction of the temple, which was built at an estimated cost of US$ 3 million raised through donations", "Solomon's Church has 4 pillars. Each pillar carrying 7 David’s stars indicating the 7 angels of the 7 churches in the Revelation", "Solomon's Church has 4 towers. Each tower carrying a crown. The four towers indicate 'the Crown of Salvation', 'the Crown of Righteousness', 'the Crown of Life' and 'the Crown of Overcomer'"];
var mon45=["The first Siva temple at Somanath is believed to have been built at some unknown time in the past", "Somnath Temple is said to be safely hiding the famous Syamantak Mani within the hollowness of Shivalinga, the Philosopher’s stone, which is associated with Lord Krishna. The stone is said to be magical, which was capable of producing gold. It is also believed that stone had alchemic and radioactive properties and thus it remains floating above the ground", "Somanath is believed to be the place where Lord Krishna ended his Lila and thereafter left for heavenly abode, therefore it is dubbed as Eternal Shrine"];
var mon46=["The wheel of chariot of Konark Sun Temple was made and established in such a way that it can tell you the time. There are total 8 spokes in the wheel. Each spoke represents a pahar (3 hours). Eight spokes represents 24 hours", "When seen from outside during dawn or sunrise, the chariot-shaped Konark Sun Temple appears to be emerging from the depths of the blue sea carrying the sun", "Konark Sun Temple is among those few temples of India whose construction and planning records have been preserved. These records were written in the Sanskrit language in Odiya Script and has been preserved in the form of palm-leaf manuscripts", "The name Konark came from the combination of two sanskrit words kona and ark. Meaning of Kona is angle and the meaning of ark is sun"];
var mon47=["Agra was not supposed to be the original site of the Taj Mahal. Mumtaz Mahal, for whom the Taj is built, died during childbirth not in Agra but rather in a city called Burhanpur located in present-day Madhya Pradesh. Burhanpur was the original resting place of the empress, but couldn’t supply enough white marble to construct the monument and so, Mumtaz Mahal’s remains were transported to Agra", "The construction of Taj Mahal started in 1631 and got completed in 1653 AD; 20,000 workers worked day and night together for 22 years", "Lord Curzon, the Viceroy of India dedicated a great deal of time and money to the Taj Mahal. The bronze lamp seen hanging over the false mausoleums of Shah Jahan and Mumtaz Mahal took two long years to make and has the inscription: 'Presented to the Tomb of Mumtaz Mahal by Lord Curzon, Viceroy 1906'", "The four minarets on the four corners of the Taj Mahal are not perfectly perpendicular. These minarets were built tilting outwards to protect the Taj at a time of natural calamity such as an earthquake. In such an occasion the minarets will fall outside and the main building will be saved", "While a large section of the population that the artisans of Taj Mahal were amputated, there is no evidence supporting the story. Shah Jahan assigned the artisans other projects after the completion of the Taj Mahal and thus it can be safely assumed that they had their hands intact"];
var mon48=["The Tirupati Balaji temple is rightly called the Bhuloka Vaikuntam – the abode of Vishnu on earth. Thus, it is believed that Lord Vishnu has manifested Himself in this temple during this Kali age to guide and direct His devotees towards salvation", "For the ritual worship of the deities housed in the Tirupati Balaji Temple, the flowers, clarified butter, milk, butter-milk, holy leaves etc. are sourced from an undisclosed village located about twenty two kilometres away from Tirupati. The little village has never been seen or visited by any outsider except its own people", "The hair worn by Lord Balaji in Tirupati Balaji Temple is silky, smooth, tangle-free, and absolutely real. The story behind those faultless locks goes like this – Lord Balaji, during his regime on earth, lost some of his hair in an unexpected mishap. A Gandharva Princess named Neela Devi quickly took note of this incident, and cut a portion of her glorious mane. She offered her chopped locks humbly to the deity and requested him to plant them on his head. Pleased with her devotion, the god accepted the kind offering and promised that whoever visits his shrine and sacrifices his/her hair at his feet will be blessed. Ever since, it has been a custom among devotees to shave their head off in the temple before or after their desires are fulfilled", "The idol of Lord Tirupati Balaji placed in Tirupati Balaji Temple may appear to be standing in the centre of the sanctum sanctorum, but technically, it is not so. The idol is actually placed in the right hand corner of the shrine", "The sound of enormous sea waves can be heard if one puts his/her ear on the back of the deity’s image housed in the Tirupati Balaji Temple", "The light of the earthen lamps placed before the idol of the deity in the sanctum sanctorum of the Tirupati Balaji Temple never gets extinguished. There are no reliable records about the time when these lamps were lit and who lit them. All that is known is that they have been burning since a long time and will continue to do so", "Long ago, in 19th century India, the King of the region imposed death sentence on twelve people for committing a heinous crime. The twelve of them were hung by their necks until death. Post death, the body of the deceased criminals were left hanging on the walls of the temple of Tirupati Balaji. It was at that time the deity himself appeared", "For an inexplicable reason, the back of the idol in the Tirputi Balaji Temple always remains moist, despite the priests labouring to keep it dry"];
var mon49=["Ujjayanta Palace was built by Tripura king, Maharaja Radha Kishore Manikya of the Manikya dynasty, between 1899 and 1901", "The two-storied Ujjayanta Palace has three large domes, the largest of which is 86 ft (26 m) high, and which rests atop a four-storied central tower", "Ujjayanta Palace is now a state museum, popularly known for its display of lifestyle, arts and cultural artefacts, and utility crafts of communities residing in Northeast India"];
var mon50=["The Victoria Memorial, one of the top historical places in Kolkata, is the brainchild of Lord Curzon, a Viceroy of India", "The marble structure of Victoria Memorial features 25 galleries, a huge collection of books and works of art. A statue of Queen Victoria is placed inside the memorial", "Before the magnificent architectural structure of Victoria Memorial was erected as one of the greatest architectural wonders in Kolkata by the British during the colonial rule, the location housed the Presidency Jail, which was later turned to dust and reconstructed in Alipore, to build the memorial", "Much like the Taj Mahal, the Victoria Memorial is also built in Makrana marbles from Rajasthan. The dome and its other architectural structures resemble the design of the Taj. It is a perfect blend of the British and Mughal architecture, also known as Indo-Saracenic Revival architecture, which was much followed by the British in the 19th century and the total cost of which was 1 crore and 5 lakh Rupees when it was constructed", "The sixteen foot tall black bronze statue mounted at the top of the great dome of Victoria Memorial is the figure of “Angel of Victory” that rotates with wind"];
var mon51=["The epitaph inscribed on Kohima War Cemetery reads: 'Here, around the tennis court of the deputy commissioner, lie men who fought in the battle of Kohima in which they and their comrades finally halted the invasion of India by the forces of Japan in April 1944'", "The Kohima War Ccemetery contains 1,420 Commonwealth burials of the Second World War and 1 non-war burial", "At the highest point in the Kohima War Cemetery stands the Kohima Cremation Memorial, commemorating 917 Hindu and Sikh soldiers whose remains were cremated in accordance with their faith", "At the lower end of the Kohima War Cemetery, near the entrance, is a memorial to the 2nd Division. It bears the inscription: 'When you go home Tell them of us and say, For your tomorrow, We gave our today'", "The Kohima War Cemetery was designed by Colin St. Claire Oakes", "The British National Army Museum in 2013 declared the battle of Imphal and Kohima as 'Britain’s greatest battle'", "The War Cemetry in Kohima is a significant historical landmark dedicated to as many as 10,000 brave soldiers of the 2nd British Division of Allied Forces who gave up their lives in World War II at Kohima during the year 1944. Kohima War Cemetry, earlier known as Garrison Hill, initially served as a tennis ground of the Deputy Commissioner and later got transformed into a battle ground"];
var mon52=["The Kachari Ruins are a series of mushroom domed pillars that were created by the Dimasa Kachari Kingdoms that ruled before the Ahom invasion during the 13th century", "The purpose and origin of the pillars at the Kachari Ruins are mysterious; few of the pillars stand in full glory while others are crumbled down. It is believed that a game similar to that of chess was played here with the mushroom shaped dooms", "It is believed that the structures of Kachari Ruins are a symbol of Aryan civilization that flourished in the deep recesses of the north eastern part of the wealthy Indian sub continental Aryan civilization. Many may find the structures of different wild animals and deities of Aryan origin in the sculptures of the mushroom domes","The Kachari Kingdom was a powerful kingdom in medieval Assam. Dimapur was the capital of ancient Kachari Dynasty and the relics of the great rulers can still be found in Dimapur. The origin of the Kachari Kingdom is not clear. The rulers belonged to the Dimasa people, part of the greater Bodo-Kachari ethnic group"];
var mon53=["The Golden Pagoda is known to the local Tai-Khamti tribal people as ‘Khongmu-kham’","The Buddha statue inside the Golden Pagoda was donated by Ven Prakhu Pabhavana, the chief monk of the Wat Aranjikavas of Thailand","A sum of 3 crore was spent by Arunachal politician Chowna Mein, who was the local MLA in building the Golden Pagoda"];
var mon54=["Chillipam Gompa is the only Indian monastery that has been built exclusively by a Chinese architect. This is why a large amount of Chinese architectural evidence can be found across the parts of monastery","The actual name of the Chillipam Monastery is  'Sang ngag Choekhar Dargyeling Monastery'"];
var mon55=["Tawang Monastery is the largest monastery in India and second largest in the world after the Potala Palace in Lhasa, Tibet","Tawang Monastery is known in Tibetan as Gaden Namgyal Lhatse, which translates to 'celestial paradise in a clear night' ","Tawang Monastery was founded by Merak Lama Lodre Gyatso in 1680-1681 in accordance with the wishes of the 5th Dalai Lama, Ngawang Lobsang Gyatso","According to a legend, a white horse of the Prince of Lhasa had wandered into Monpa region. People found the horse grazing at the present location of the monastery. The people of the area then worshipped the horse and to honour the sacred site, the Tawang Monastery was built at the site"];
var mon56=["The beautiful Naulakha temple is dedicated to Goddess Radha and Lord Krishna","The construction of Naulakha Mandir began with the donation of nine lakh rupees by queen Charushila of Pathuria Ghat, a royal family from Kolkata, and hence the temple has been endowed the name, 'naulakha' ('nau' meaning nine and 'lakha' meaning lakh)","The construction of the Naulakha Temple is similar to that of the temple of Ramakrishna in Belur"];

/*shuffle array using Fisher-Yates shuffle so that states appear in random order*/
function shuffle(array) {
  var currentIndex = array.length,  randomIndex;
  // While there remain elements to shuffle...
  while (currentIndex != 0) {
  // Pick a remaining element...
  randomIndex = Math.floor(Math.random() * currentIndex);
  currentIndex--;
  // And swap it with the current element.
  [array[currentIndex], array[randomIndex]] = [
    array[randomIndex], array[currentIndex]];}
  return array;}
  var arr = [1, 2, 3, 4];
  shuffle(arr);

/*selecting random monuments and corresponding states image to dispaly on window load*/
window.onload = chooseMon;
function chooseMon() {
 var a = Math.floor(Math.random() * ((Object.keys(dict).length)-1))+1;
 document.getElementById("mon1").src = "monuments/mon"+a+".png";
 document.getElementById("state"+arr[0]).src = dict["monuments/mon"+a+".png"];

 do {var b = Math.floor(Math.random() *((Object.keys(dict).length)-1))+1;}
 while (b==a)
 document.getElementById("mon2").src = "monuments/mon"+b+".png";
 document.getElementById("state"+arr[1]).src = dict["monuments/mon"+b+".png"];

 do{var c = Math.floor(Math.random() *((Object.keys(dict).length)-1))+1;}
 while (c==b || c==a)
 document.getElementById("mon3").src = "monuments/mon"+c+".png";
 document.getElementById("state"+arr[2]).src = dict["monuments/mon"+c+".png"];

 do{var d = Math.floor(Math.random() * ((Object.keys(dict).length)-1))+1;}
 while (d==c || d==b || d==a)
 document.getElementById("mon4").src = "monuments/mon"+d+".png";
 document.getElementById("state"+arr[3]).src = dict["monuments/mon"+d+".png"];
}
 
let al=document.createElement('a');
al.target='_self';
al.href='gamepage.html';

function mySubmit(){
for (let i = 1; i < 5; i++) {

var x = document.getElementById('dropBox'+i);
var sss = x.getElementsByTagName('img')[0];
var ss=sss.src;
var mmm = x.getElementsByTagName('img')[1];
if (typeof(mmm) == 'undefined'){
  window.alert("Please drag and drop all Monuments in respective States")
  return None;
}
var mm=mmm.src;
var index1 = mm.indexOf("monuments");
var index2 = mm.indexOf(".png")
index1=index1+10;
m=mm.slice(index1,index2);

index1 = ss.indexOf("states");
s=ss.slice(index1);
console.log(s);

mtemp=shuffle(eval(m));
var fact=mtemp[Math.floor(Math.random() * ((mtemp.length)-1))+1];
var tttt=dict["monuments/"+m+".png"];
if (dict["monuments/"+m+".png"]==s){
window.alert("Monument "+i+". Correct answer! \nFun Fact\n"+fact);
} else{
if (window.confirm("Monument "+i+". Wrong Answer! Better Luck Next Time\nPlay Again?")){
    al.click();
    return None;}
}
} 
if (window.confirm("Play Again?")){
    al.click();}
}

function displayHint(){
  var x=event.target;
  x=x.id;
  x=x.slice(4);   //x=1
  var monumentNo="mon"+x;   //monument number from 1 to 4
  var temp=document.getElementById(monumentNo).src;
  var index1=temp.indexOf("monuments");
  var index2=temp.indexOf(".png");
  var monument=temp.slice(index1+10,index2);
  var state=dict["monuments/"+monument+".png"];
  index1=state.indexOf("states");
  index2=state.indexOf(".png");
  state=state.slice(index1+7,index2);   //state for which hint to be diplayed
  var hint=eval(state)[0];
  console.log(hint);
  window.alert("Hint: \n"+hint);
  window.eval(state).push(window.eval(state).shift());
}